# Generated by Django 4.1.5 on 2023-02-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ph", "Philippines"),
                    ("pl", "Poland"),
                    ("us", "United States"),
                    ("uk", "United Kingdom"),
                    ("ca", "Canada"),
                ],
                default="ph",
                max_length=250,
            ),
        ),
    ]
